---
title: "Hepatisis data analysis"
output:
  pdf_document: default
  html_document:
    number_sections: yes
---

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(visdat)
library(caret)
library(RANN)
library(corrplot)
library(plotly)
library(ggplot2)
library(resample)
library(DataExplorer)
library(imputeMulti)
library(mice)
library(rmarkdown)
library(repr)
```

# Introduction 

First rows of our data frame.


```{r}
df <- read.table("hepatitis.data", sep = ",")
colnames(df) <- c("Class","Age","Sex","Steroid","Antivirals","Fatigue","Malaise","Anorexia","LiverBig","LiverFirm","SpleenPalpable","Spiders","Ascites","Varices","Bilirubin","AlkPhosphate","Sgot","Albumin","Protime","Histology") # nolint
# attach(df)
```

```{r}
head(df)
```

# Preparing data
```{r}
df[df == "?"] <- NA

df <- mutate_all(df, function(x) as.numeric(as.character(x)))
categorical <- c(1, 3:14, 20)
df[, categorical] <- replace(df[, categorical], df[, categorical] == 2, 0)
df[, categorical] <-  lapply(df[, categorical], as.factor)
```

```{r}
sum(rowSums(is.na(df)) != 0) # we cannot remove these rows!
sum(is.na(df))
vis_dat(df)
# vis_dat(df2)
```

```{r}
plot_missing(df)
```

```{r}
md.pattern(df)
```


```{r}
df.new <- mutate_all(df, function(x) as.numeric(as.character(x)))
data_transform <- preProcess(df.new, method = "knnImpute")
data_transform2 <- preProcess(df.new, method = "bagImpute")
data_transform3 <- preProcess(df.new, method = "medianImpute")

df1 <- predict(data_transform, df.new)
df2 <- predict(data_transform2, df.new)
df3 <- predict(data_transform3, df.new)

df2[c(4:14, 16:17, 19)] <- round(df2[c(4:14, 16:17, 19)])
df3[c(4:14, 16:17, 19)] <- round(df3[c(4:14, 16:17, 19)])

```


```{r echo=FALSE}
for (i in 1:20) {
  column <- df.new[, i]
  if (i %in% c(15, 18)) {
    df1[, i] <- df1[, i] * sd(na.omit(column)) + mean(na.omit(column))
  } else {
    df1[, i] <- round(df1[, i] * sd(na.omit(column)) + mean(na.omit(column)))
  }
}

# categorical <- c(1, 3:14, 20)
# df1[, categorical] <- replace(df1[, categorical], df1[, categorical] == 2, 0)
# df1[, categorical] <-  lapply(df1[, categorical], as.factor)
# df2[, c(2, 16:17, 19)] <- lapply(df2[, c(2, 16:17, 19)], as.integer)
```

```{r results="hide"}
methods = c(" "," "," ","logreg"," ","logreg","logreg","logreg","logreg","logreg","logreg","logreg","logreg","logreg","pmm","pmm","pmm","pmm","pmm"," ")
imp_single <- mice(df, m = 1, method = methods) # Impute missing values
df4 <- complete(imp_single)         # Store imputed data

imp_multi <- mice(df, method = methods)  # Impute missing values multiple times
df5 <- complete(imp_multi, 1)
```

```{r}
# pmm, predictive mean matching (numeric data) 
# logreg, logistic regression imputation (binary data, factor with 2 levels) 
```


```{r}
summary(df)
summary(df1)
summary(df2)
summary(df3)
summary(df4)
summary(df5)
```

```{r}
colVars(na.omit(df.new))
colVars(df2)
colVars(df3)
colVars(df4)
colVars(df5)
```

```{r echo=FALSE}
df$method <-  c(rep("omit", nrow(df)))
df1$method <- c(rep("knn", nrow(df1)))
df2$method <- c(rep("bag tree", nrow(df2)))
df3$method <- c(rep("median", nrow(df3)))
df5$method <- c(rep("mice", nrow(df5)))
df_all <- rbind(df, df1, df2, df3, df5)
```
```{r echo=FALSE}
# n <- 9 # 10, 11, 12, 13, 14
# missingness <- c(rep("With Missings", 2), rep("Post Imputation: knnImpute", 2), rep("Post Imputation: bagImpute", 2), rep("Post Imputation: mediumImpute", 2), rep("Post Imputation: mice", 2), rep("Post Imputation: multiply mice", 2)) # Pre/post imputation
# Category <- as.factor(rep(names(table(df[n])), 6))                   # Categories
# Count <- c(as.numeric(table(df[n])), as.numeric(table(df1[n])), as.numeric(table(df2[n])), as.numeric(table(df3[n])), as.numeric(table(df4[n])), as.numeric(table(df5[n])))     # Count of categories
 
# data_barplot <- data.frame(missingness, Category, Count)           # Combine data for plot
 

# ggplot(data_barplot, aes(Category, Count, fill = missingness)) +   # Create plot
#   geom_bar(stat = "identity", position = "dodge") + 
#   scale_fill_brewer(palette = "Set2") +
#   theme(legend.title = element_blank())
```
```{r echo=FALSE}
# ggplot(df_all, aes(x = LiverBig, fill = method)) +   # Create plot
#   scale_fill_brewer(palette = "Set2") +
#   geom_bar(position = "dodge")
```
```{r echo=FALSE}
# ggplot(df_all, aes(x = Protime, fill = method)) +
#   geom_density(alpha = 0.5)
```

```{r fig2, fig.height = 10, fig.width = 10, fig.align = 'center', warning=FALSE, message=FALSE}
ggplot(df_all, aes(x = Protime, color = method)) +
  scale_fill_brewer(palette = "Set2") +
  geom_density(size = 1.25) +
  facet_grid(Class ~ .)
```

```{r echo=FALSE}
# col.cat.with.mv <- c(4)
# imputeEM_none <- multinomial_impute(df[col.cat.with.mv], method = "EM", conj_prior = "non.informative", verbose = TRUE)
 ```

# EDA

```{r}
plot_bar(df_all, by = "method", by_position = "dodge")
```
```{r}
plot_boxplot(df5, by = "Class")
```

```{r fig1, fig.height = 10, fig.width = 10, fig.align = 'center'}
cor_matrix <- cor(df2[, sapply(df2, is.numeric)], method = "pearson")
corrplot(cor_matrix, tl.col = "black", addCoef.col = 1, number.cex = 0.9)
```
```{r echo=FALSE}
# plot_histogram(df)
# plot_bar(df)
# plot_qq(df)
# plot_boxplot(df, by = "Class")

## Charts: continuous quantitative data
# Typical questions:
  # 
  # - Uni- or multi-modal distribution?
  # - Symmetric or left- / right-skewed distribution?
  # - Mode / modal interval?
  # - Does the distribution resemble a normal, uniform distribution?

## Charts: discrete quantitative data
# Typical questions:
  #   
  #   - The most frequent value?
  #   - min / max?
  #   - Frequencies of consecutive values?

## Charts: qualitative data
  # Analysis within groups: Why do customers leave?
```
